module Constants
  BIKE_MAX_DISTANCE = 30
  BIKE_MAX_WEIGHT = 10
  BIKE_MAX_SPEED = 10

  CAR_MAX_WEIGHT = 100
  CAR_MAX_SPEED = 50
  CAR_DEFAULT_DISTANCE = 2000

  DEFAULT_BIKES_COUNT = 8
  DEFAULT_CARS_COUNT = 6
end
